apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-api
  labels:
    app: {{ .Values.env }}-api
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.env }}-api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-api
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: main
          image: {{ .Values.image.registry }}/{{ .Values.image.backend }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          args: ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:8000", "replant.wsgi:application"]
          envFrom:
            - configMapRef:
                name: {{ .Values.env }}
            - secretRef:
                name: {{ .Values.env }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests:
              memory: 1Gi
              cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-api
  labels:
    app: {{ .Values.env }}-api
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.env }}-api
    release: {{ .Release.Name }}
