apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: replant
  labels:
    app: replant
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/proxy-body-size: 2m
     cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.appDomain }}
    - {{ .Values.marketplaceDomain }}
    secretName: kubernetes-tls
  rules:
    - host: {{ .Values.appDomain }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env }}-api
                port:
                  number: 80
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env }}-api
                port:
                  number: 80
          - path: /django-static/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env }}-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env }}-upload-app
                port:
                  number: 80
    - host: {{ .Values.marketplaceDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env }}-marketplace-app
                port:
                  number: 80
