# Generated by Django 5.0.1 on 2024-01-24 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0002_add_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name",), "verbose_name_plural": "countries"},
        ),
    ]
