# Generated by Django 5.0.1 on 2024-01-31 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0005_species"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantingorganization",
            options={
                "verbose_name": "planting organization / community",
                "verbose_name_plural": "planting organizations / communities",
            },
        ),
        migrations.AlterField(
            model_name="assignedspecies",
            name="planting_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="replant.plantingorganization",
                verbose_name="planting organization / community",
            ),
        ),
        migrations.AlterField(
            model_name="passcode",
            name="planting_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passcodes",
                to="replant.plantingorganization",
                verbose_name="planting organization / community",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="planting_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="replant.plantingorganization",
                verbose_name="planting organization / community",
            ),
        ),
    ]
