# Generated by Django 5.0.2 on 2024-02-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0011_plantawaitingsponsor_plant_sponsor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlantToReview",
        ),
        migrations.RenameModel(
            old_name="Plant",
            new_name="Tree",
        ),
        migrations.CreateModel(
            name="TreeToReview",
            fields=[],
            options={
                "verbose_name_plural": "trees to review",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("replant.tree",),
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='assigned_plants',
            new_name='assigned_trees',
        ),
        migrations.RenameIndex(
            model_name="tree",
            new_name="replant_tre_review__850254_idx",
            old_name="replant_pla_review__59281e_idx",
        ),
    ]
