# Generated by Django 5.0.2 on 2024-02-22 15:28

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0012_rename_plant_tree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nft",
            fields=[],
            options={
                "verbose_name_plural": "NFTs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("replant.tree",),
        ),
        migrations.CreateModel(
            name="TreeToMint",
            fields=[],
            options={
                "verbose_name_plural": "trees to mint",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("replant.tree",),
        ),
        migrations.AddField(
            model_name="tree",
            name="image_cid",
            field=models.URLField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tree",
            name="metadata_cid",
            field=models.URLField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tree",
            name="minting_state",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TO_BE_MINTED", "To Be Minted"),
                    ("MINTED", "Minted"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="nft_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="nft_mint_tx",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="tree",
            index=models.Index(
                fields=["minting_state"], name="replant_tre_minting_270fa0_idx"
            ),
        ),
    ]
