# Generated by Django 5.0.2 on 2024-02-23 10:18

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0012_rename_plant_tree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nft",
            fields=[],
            options={
                "verbose_name_plural": "NFTs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("replant.tree",),
        ),
        migrations.CreateModel(
            name="TreeToMint",
            fields=[],
            options={
                "verbose_name_plural": "trees to mint",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("replant.tree",),
        ),
        migrations.RemoveIndex(
            model_name="tree",
            name="replant_tre_review__850254_idx",
        ),
        migrations.AddField(
            model_name="tree",
            name="image_cid",
            field=models.URLField(
                blank=True, default="", max_length=128, verbose_name="image CID"
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="metadata_cid",
            field=models.URLField(
                blank=True, default="", max_length=128, verbose_name="metadata CID"
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="minting_state",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TO_BE_MINTED", "To Be Minted"),
                    ("MINTED", "Minted"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="nft_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True, verbose_name="NFT ID"
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="nft_mint_tx",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="tree",
            name="review_state",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
