# Generated by Django 5.0.2 on 2024-03-07 09:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0013_nft_treetomint_tree_image_cid_tree_metadata_cid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="assigned_trees_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Assigned trees [USD]",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="nft_ordered_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Uncapped when empty",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="NFT ordered [USD]",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="nft_ordered",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Uncapped when empty",
                null=True,
                verbose_name="NFT ordered",
            ),
        ),
    ]
