# Generated by Django 5.0.2 on 2024-03-05 11:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0013_nft_treetomint_tree_image_cid_tree_metadata_cid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="assigned_trees_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Assigned trees [USD]",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="nft_ordered_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Uncapped when zero",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="NFT ordered [USD]",
            ),
        ),
    ]
