# Generated by Django 5.0.2 on 2024-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0014_sponsor_additional_info_sponsor_assigned_trees_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=models.CharField(
                choices=[
                    ("Etc/GMT-14", "UTC+14"),
                    ("Etc/GMT-13", "UTC+13"),
                    ("Etc/GMT-12", "UTC+12"),
                    ("Etc/GMT-11", "UTC+11"),
                    ("Etc/GMT-10", "UTC+10"),
                    ("Etc/GMT-9", "UTC+9"),
                    ("Etc/GMT-8", "UTC+8"),
                    ("Etc/GMT-7", "UTC+7"),
                    ("Etc/GMT-6", "UTC+6"),
                    ("Etc/GMT-5", "UTC+5"),
                    ("Etc/GMT-4", "UTC+4"),
                    ("Etc/GMT-3", "UTC+3"),
                    ("Etc/GMT-2", "UTC+2"),
                    ("Etc/GMT-1", "UTC+1"),
                    ("UTC", "UTC"),
                    ("Etc/GMT+1", "UTC-1"),
                    ("Etc/GMT+2", "UTC-2"),
                    ("Etc/GMT+3", "UTC-3"),
                    ("Etc/GMT+4", "UTC-4"),
                    ("Etc/GMT+5", "UTC-5"),
                    ("Etc/GMT+6", "UTC-6"),
                    ("Etc/GMT+7", "UTC-7"),
                    ("Etc/GMT+8", "UTC-8"),
                    ("Etc/GMT+9", "UTC-9"),
                    ("Etc/GMT+10", "UTC-10"),
                    ("Etc/GMT+11", "UTC-11"),
                    ("Etc/GMT+12", "UTC-12"),
                ],
                default="UTC",
                max_length=40,
            ),
        ),
    ]
