# Generated by Django 5.0.2 on 2024-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0015_user_time_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MINTING_SUCCEED", "Minting Succeed"),
                            ("MINTING_FAILED", "Minting Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True)),
                ("details", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "History log",
                "verbose_name_plural": "History",
            },
        ),
    ]
