# Generated by Django 5.0.2 on 2024-03-14 11:33

from django.db import migrations
from django.db.models import F


def set_captured_at(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")

    Tree.objects.update(captured_at=F("created_at"))


def unset_captured_at(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")

    Tree.objects.update(captured_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0019_tree_captured_at"),
    ]

    operations = [
        migrations.RunPython(set_captured_at, unset_captured_at)
    ]
