# Generated by Django 5.0.2 on 2024-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0020_set_captured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tree",
            name="captured_at",
            field=models.DateTimeField(),
        ),
    ]
