# Generated by Django 5.0.2 on 2024-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0021_alter_tree_captured_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreesCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centroid_x", models.FloatField()),
                ("centroid_y", models.FloatField()),
                ("zoom", models.PositiveIntegerField()),
                ("number_of_trees", models.PositiveIntegerField()),
            ],
        ),
    ]
