# Generated by Django 5.0.2 on 2024-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0022_treescluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="treescluster",
            name="relative_size",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
