# Generated by Django 5.0.2 on 2024-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0023_treescluster_relative_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="treescluster",
            name="tile_index",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
