# Generated by Django 5.0.2 on 2024-03-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0024_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOCATION_SUCCEEDED", "Location Succeeded"),
                            ("LOCATION_FAILED", "Location Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField()),
                ("os", models.CharField(max_length=50)),
                ("os_version", models.CharField(max_length=50)),
                ("browser", models.CharField(max_length=50)),
                ("browser_version", models.CharField(max_length=50)),
                ("device", models.CharField(max_length=50)),
                ("error_name", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="accuracy [m]",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User history log",
                "verbose_name_plural": "User history",
            },
        ),
    ]
