# Generated by Django 5.0.2 on 2024-03-27 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0024_treescluster_tile_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treescluster",
            old_name="centroid_x",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="treescluster",
            old_name="centroid_y",
            new_name="lon",
        ),
    ]
