# Generated by Django 5.0.2 on 2024-04-10 08:13

from django.db import migrations, models
import replant.models.sponsor


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0025_userhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to=replant.models.sponsor.logo_upload_to
            ),
        ),
    ]
