# Generated by Django 5.0.2 on 2024-04-17 12:33

import replant.models.sponsor
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0025_userhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="bio",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to=replant.models.sponsor.logo_upload_to
            ),
        ),
    ]
