# Generated by Django 5.0.2 on 2024-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0025_rename_centroid_x_treescluster_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treescluster",
            name="relative_size",
        ),
    ]
