# Generated by Django 5.0.4 on 2024-04-04 12:43

from django.db import migrations

TREE_ZOOM = 9


def _get_tile_index(lat: float, lon: float) -> int:
    grid_size = int(4 ** (max(0, TREE_ZOOM - 1)))
    tile_size = 360 / grid_size
    y = int((lat + 90) / tile_size)
    x = int((lon + 180) / tile_size)
    return y * grid_size + x


def set_tile_index(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")

    trees = Tree.objects.all()

    for tree in trees:
        tree.tile_index = _get_tile_index(float(tree.latitude), float(tree.longitude))

    Tree.objects.bulk_update(trees, ["tile_index"])


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0026_treescluster"),
    ]

    operations = [
        migrations.RunPython(set_tile_index, migrations.RunPython.noop),
    ]
