# Generated by Django 5.0.2 on 2024-04-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0028_fill_tree_tile_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="minted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="tree",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfts",
                to="replant.sponsor",
            ),
        ),
    ]
