# Generated by Django 5.0.2 on 2024-04-23 08:41

from django.db import migrations
from django.db.models import F


def set_minted_at(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")

    Tree.objects.filter(minting_state="MINTED").update(minted_at=F("updated_at"))


def unset_minted_at(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")

    Tree.objects.update(minted_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("replant", "0029_tree_minted_at_alter_tree_sponsor"),
    ]

    operations = [
        migrations.RunPython(set_minted_at, unset_minted_at)
    ]

