# Generated by Django 5.0.2 on 2024-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replant", "0030_set_minted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="storage_provider",
            field=models.CharField(
                choices=[("NFT_STORAGE", "Nft Storage"), ("FILEBASE", "Filebase")],
                default="FILEBASE",
                max_length=32,
            ),
        ),
    ]
