# Generated by Django 5.0.2 on 2024-11-27 12:09

from django.db import migrations
from replant.models.tree import Tree as TreeModel

def asign_already_minted_trees_to_nft_storage(apps, schema_editor):
    Tree = apps.get_model("replant", "Tree")
    Tree.objects.filter(minting_state=TreeModel.MintingState.MINTED).update(nft_storage=TreeModel.Storage.NFT_STORAGE)

class Migration(migrations.Migration):

    dependencies = [
        ("replant", "0031_tree_nft_storage"),
    ]

    operations = [migrations.RunPython(asign_already_minted_trees_to_nft_storage, migrations.RunPython.noop)]
